dnl Product version for header files.  Maintained by dist/s_version
VERSION_MAJOR=0
VERSION_MINOR=2
VERSION_PATCH=0
VERSION_STRING='"0.2.0 (2014-03-01)"'

AC_SUBST(VERSION_MAJOR)
AC_SUBST(VERSION_MINOR)
AC_SUBST(VERSION_PATCH)
AC_SUBST(VERSION_STRING)

VERSION_NOPATCH=0.2
AC_SUBST(VERSION_NOPATCH)
