dnl Product version for header files. Maintained by dist/bump-version.sh
VERSION_MAJOR=0
VERSION_MINOR=3
VERSION_PATCH=1
VERSION_STRING='"0.3.1 (2014-07-06)"'

AC_SUBST(VERSION_MAJOR)
AC_SUBST(VERSION_MINOR)
AC_SUBST(VERSION_PATCH)
AC_SUBST(VERSION_STRING)

VERSION_NOPATCH=0.3
AC_SUBST(VERSION_NOPATCH)
