dnl Product version for header files. Maintained by dist/bump-version.sh
VERSION_MAJOR=0
VERSION_MINOR=4
VERSION_PATCH=0
VERSION_STRING='"0.4.0 (2014-09-05)"'

AC_SUBST(VERSION_MAJOR)
AC_SUBST(VERSION_MINOR)
AC_SUBST(VERSION_PATCH)
AC_SUBST(VERSION_STRING)

VERSION_NOPATCH=0.4
AC_SUBST(VERSION_NOPATCH)
