BINARIES = bin/test bin/tokenizer
SHARED_LIBS = lib/libschwa.$(SHARED_LIB_SUFFIX)

MSGPACK_OBJECTS = src/lib/schwa/msgpack/wire.o
TOKENIZER_OBJECTS = src/lib/schwa/tokenizer/tokenizer.o src/lib/schwa/tokenizer/streams/debug_text.o src/lib/schwa/tokenizer/streams/text.o

OBJECTS = $(MSGPACK_OBJECTS) $(PORT_OBJECTS) $(TOKENIZER_OBJECTS)

UNIT_TEST_OBJECTS = src/tests/unit_tests/main.o src/tests/unit_tests/schwa/msgpack/wire.o
UNIT_TEST_BINARY = bin/_unit_tests
TEST_BINARIES = $(UNIT_TEST_BINARY)

GENERATED_SOURCES = src/lib/schwa/tokenizer/tokenizer.cc


.PHONY: all clean depends test wc

all: $(BINARIES) $(SHARED_LIBS)

clean:
	-find src -name "*.gch" -exec rm -f {} \;
	-find src -name "*.o" -exec rm -f {} \;
	-find lib \( -name "*.$(SHARED_LIB_SUFFIX)" -or -name "*.so" \) -exec rm -f {} \;
	-rm -f $(BINARIES) $(TEST_BINARIES)
	-rm -f $(GENERATED_SOURCES)

depends:
	src/scripts/depends "$(CXX) -MM $(INCLUDE) $(DEFINES) $(PYAPI_INCLUDE)" `find src -name '*.cc' | grep -v ^src/lib/schwa/port` $(PORT_OBJECTS:%.o=%.cc) > Makefile.depends

wc:
	find src -name "*.cc" -or -name "*.h" | grep -v ^src/tests/ | xargs wc -l


# -------------------------------------------------------------------------------
# base targets
# -------------------------------------------------------------------------------
%.h.gch: %.h
	$(CXX) -x c++-header $(CXXFLAGS) -o $@ $<

bin/test: src/main/test.o $(BASE_OBJECTS) $(MSGPACK_OBJECTS)
	$(CXX) $^ $(LDFLAGS) -o $@

bin/tokenizer: src/main/tokenizer.o $(BASE_OBJECTS) $(TOKENIZER_OBJECTS)
	$(CXX) $^ $(LDFLAGS) -o $@

lib/libschwa.$(SHARED_LIB_SUFFIX): $(OBJECTS)
	$(CXX) $(SHARED_LIB_LDFLAGS) -o $@ $^ $(LIBS)


# -------------------------------------------------------------------------------
# generated sources
# -------------------------------------------------------------------------------
src/lib/schwa/tokenizer/tokenizer.o: src/lib/schwa/tokenizer/tokenizer.cc
	$(CXX) $(RAGEL_CXXFLAGS) -c -o $@ $<

src/lib/schwa/tokenizer/tokenizer.cc: src/ragel/tokenizer.rl src/ragel/rules/*.rl Makefile Makefile.targets
	$(RAGEL) -G2 -o $@ $<


# -------------------------------------------------------------------------------
# Testing
# -------------------------------------------------------------------------------
src/tests/unit_tests/%.o: src/tests/unit_tests/%.cc
	$(CXX) $(TEST_CXXFLAGS) -c -o $@ $<

$(UNIT_TEST_BINARY): $(UNIT_TEST_OBJECTS) lib/libschwa.$(SHARED_LIB_SUFFIX)
	$(CXX) $(UNIT_TEST_OBJECTS) $(LDFLAGS) $(TEST_LDFLAGS) -o $@

tests: $(UNIT_TEST_BINARY)

test: tests
	LD_LIBRARY_PATH=lib:ext/lib $(UNIT_TEST_BINARY)

