#!/bin/bash

DESTDIR="${1}"
PREFIX="${2}"
SHARED_LIBS="${3}"
BINARIES="${4}"

DESTDIR="$(cd ${DESTDIR}${PREFIX} && pwd )"

install -d -v ${DESTDIR}/{bin,include/schwa,lib}

# Install the header files.
for f in $(find src/lib -type f -name '*.h'); do
  dest_f=${f/src\/lib\//${DESTDIR}\/include\/}
  install -d -v $(dirname ${dest_f})
  install -p -m 0644 -v ${f} ${dest_f}
done

# Install the shared libraries.
for f in ${SHARED_LIBS}; do
  install -p -v ${f} ${DESTDIR}/lib
done

# Install the binaries.
for f in ${BINARIES}; do
  install -p -v ${f} ${DESTDIR}/bin
done
