#!/usr/bin/env python3
import json
import os
import sys
import urllib.request

SCRIPT_PATH = None
URL = 'http://www.w3.org/html/wg/drafts/html/master/entities.json'


def main(file, url):
  print(r'''
// Generated by: {0}
// vim: ft=ragel:
/* -*- Mode: C++; indent-tabs-mode: nil -*- */

%%{{
  machine html;

  named_character_references ='''.format(SCRIPT_PATH).lstrip(), file=file)

  data = urllib.request.urlopen(url).read().decode('utf-8')
  data = json.loads(data)
  first = True
  for name in sorted(data):
    line = ['    ']
    if first:
      first = False
      line.append('  ')
    else:
      line.append('| ')
    line.append('\'')
    line.append(name[1:-1])
    line.append('\'')
    print(''.join(line), file=file)

  print(r'''
    ;
}%%'''.lstrip('\n'), file=file)


if __name__ == '__main__':
  path = os.path.normpath(os.path.dirname(__file__))
  if path != 'src/scripts':
    print('Error: This script must be run from the top-level directory of libschwa.', file=sys.stderr)
    sys.exit(1)

  SCRIPT_PATH = os.path.join(path, os.path.basename(__file__))

  url = URL if len(sys.argv) == 1 else sys.argv[1]
  with open('src/ragel/document-structure/html/named_character_references.rl', 'w') as file:
    main(file, url)
